### ISSUE TITLE
! as shortcut for !important

### ISSUE THREAD

**Issue by talaub** [talaub/miro#26]
It should be possible to use `!` as a shortcut for `!important`

```stylus
div
    display inline !
```
compiles to
```css
div {
   display: inline !important;
}
```
