### ISSUE TITLE
Blocks inside of mixins

### ISSUE THREAD

**Issue by talaub** [talaub/miro#3]
It would be nice, if one could store blocks inside of mixins.

```stylus
$test()
    b
        font-weight bold

main
    $test()
```
would compile to
```css
main b {
    font-weight: bold;
}
```
