### ISSUE TITLE
Use variables in block-headers

### ISSUE THREAD

**Issue by talaub** [talaub/miro#5]
It would be very useful if one could use the defined variables in block-headers

```stylus
$selector = large
div.box-${selector}
    width 500px
    height 500px
```
would compile to
```css
div.box-large {
    width: 500px;
    height: 500px;
}
```
