### ISSUE TITLE
Media if-statements

### ISSUE THREAD

**Issue by talaub** [talaub/miro#9]
I'm always looking for ways to make media-queries easier to write. In addition to the short media-queries I would like to have a programming-style for media-queries.

```stylus
div.page
    width 80%

    @if (media is screen) && (width <= 600px)
        width 90%
```
```css
div.page {
    width: 80%;
}
@media screen and (max-width: 600px) {
    div.page  {
        width: 90%;
    }
}
```
